services:
  ems-postgres:
    image: postgres:16
    container_name: ems-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ems_pw
      POSTGRES_DB: emsdb
    ports:
      - "5432:5432"
    volumes:
      - ems_pg_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems -d emsdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [ems-net]
volumes:
  ems_pg_data:
networks:
  ems-net: