spring:
  profiles:
    default: local
---
spring:
  config: { activate: { on-profile: local } }
  datasource:
    url: jdbc:h2:mem:emsdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate: { ddl-auto: none }
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.show_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
server: { port: 8081 }
---
spring:
  config: { activate: { on-profile: docker } }
  datasource:
    url: jdbc:postgresql://localhost:5432/emsdb
    username: ems
    password: ems_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: { ddl-auto: validate }
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.show_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
      data-locations: classpath:data-postgresql.sql
server: { port: 8081 }